### ISSUE TITLE
空格问题

### ISSUE THREAD

**Issue by GZlkj** [FloydaGithub/LuaFormat#20]
你好 请问可以把每行的tab空格(如果那行是空的)去掉吗？

**Comment by FloydaGithub** [comment]
没弄明白你的意思~
可以说得详细一点么? 或者举个栗子???

**Comment by GZlkj** [comment]
![qq 20181126095611](https://user-images.githubusercontent.com/45257277/48988649-90e74f00-f161-11e8-97a7-c288e8cc97f4.png)
你好，就是这种空行的空格可以不要的吗
