### ISSUE TITLE
LuaFormat.format() gives "\\n" as eol

### ISSUE THREAD

**Issue by Alexey-T** [FloydaGithub/LuaFormat#3]
After i take `\\n` as eol,  it's hard to restore to orig eol's, since `\n` also exist inside strings.
Wish: add param to use normal eol's here.
but better: use normal eol's w/o param.

**Comment by FloydaGithub** [comment]
can you show me a code example?

**Comment by Alexey-T** [comment]
from . import LuaFormat
from cudatext import *

s = ed.get_text_all() #all text from Cudatext
s = LuaFormat.format(s)
ed.set_text_all(s) #set all text

**Comment by FloydaGithub** [comment]
`After i take \\n as eol, it's hard to restore to orig eol's, since \n also exist inside strings.`

I want this kind of code, I can't reproduce this Bug...
