### ISSUE TITLE
make format function get list of str

### ISSUE THREAD

**Issue by Alexey-T** [FloydaGithub/LuaFormat#5]
lua_format() gets content- **string**. 
1) wish - change it to **list of str.**
reason - you wont need to know which is line separator of lines, \n \r or other.
I use `\n`. i have resulting contents with `\\n` with 2 slash. 

2) if you change result too - to **list of str** - it is good.
inside code you can convert it to string.
but get result as list of str.

**Comment by FloydaGithub** [comment]
https://github.com/FloydaGithub/LuaFormat/blob/d1b98d79bdc887ead8ffbd48201d00c9e89bd80a/core/LuaFormat.py#L475
