### ISSUE TITLE
format error with number "1e-5"

### ISSUE THREAD

**Issue by QiuLeiQQLL** [FloydaGithub/LuaFormat#6]
before format:
![image](https://user-images.githubusercontent.com/29012144/32268533-6bfd8192-bf2a-11e7-846a-ea288da936e4.png)
after format:
![image](https://user-images.githubusercontent.com/29012144/32268553-836fc34e-bf2a-11e7-8b5a-09ba1fd800e3.png)

**Comment by FloydaGithub** [comment]
3bfff320d5bedfb1717258474080a1ee83762b94
