### ISSUE TITLE
PLoop Style Support

### ISSUE THREAD

**Issue by QiuLeiQQLL** [FloydaGithub/LuaFormat#7]
PLoop is an awesome lua oop : https://github.com/kurapica/PLoop
when i format the PLoop Style code, two problem occured
before format:
![image](https://user-images.githubusercontent.com/29012144/32269364-16210c00-bf2d-11e7-8305-360c1a3e18a4.png)
after format:
![image](https://user-images.githubusercontent.com/29012144/32269337-0341b940-bf2d-11e7-983e-b6c300911992.png)

**Comment by FloydaGithub** [comment]
079bd67226a13f6086a7a7c6e8ff1cb00d927428
解决一半了, 还差一个引号嵌套的Bug.

**Comment by QiuLeiQQLL** [comment]
@FloydaGithub 原来是个国人，哈哈。LuaFormat我一直在找，始终没找到一个能用的，最近发现这里近期有更新，弄下来试了试，竟然真的能用，棒棒哒。这个也不是PLoop style的问题，应该是匿名函数缩进的问题吧。后面那个\n明显就是bug了

**Comment by FloydaGithub** [comment]
e40d195c2e6e31d9bc566c49ab074450e0746072

谢谢你帮我测Bug啊~
你这2个问题已经修复了, 你再看看, 有什么Bug或者建议尽管提~
